ALTER TABLE "jobs"
  ADD COLUMN "otherFeesEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "otherFeesRate" DECIMAL(65,30) NOT NULL DEFAULT 3.5,
  ADD COLUMN "otherFeesAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;

ALTER TABLE "invoices"
  ADD COLUMN "otherFeesEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "otherFeesRate" DECIMAL(65,30) NOT NULL DEFAULT 3.5,
  ADD COLUMN "otherFeesAmount" DECIMAL(65,30) NOT NULL DEFAULT 0;
