export type MockInventoryItem = {
  barcode?: string;
  category: string;
  cost: number;
  description: string;
  id: string;
  itemStatus: "Active" | "Inactive";
  location: string;
  maxStock: number;
  notes?: string;
  product: string;
  reorderPoint: number;
  sku: string;
  stock: number;
  taxable: boolean;
  taxRate: number;
  unit: string;
  unitPrice: number;
  vendor?: string;
};

export const mockInventoryItems: MockInventoryItem[] = [
  {
    id: "inv-1001",
    sku: "WH-1001",
    product: "Wireless Headphones Pro",
    category: "Electronics",
    description: "Noise-cancelling wireless headphones with travel case.",
    stock: 145,
    reorderPoint: 40,
    maxStock: 180,
    location: "Warehouse A",
    unit: "each",
    cost: 52.5,
    unitPrice: 89.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735001001001",
    vendor: "Northstar Audio",
    notes: "Best seller. Keep extra stock before holiday promotions.",
  },
  {
    id: "inv-2045",
    sku: "KB-2045",
    product: "Mechanical Keyboard RGB",
    category: "Electronics",
    description: "Wired mechanical keyboard with programmable RGB lighting.",
    stock: 23,
    reorderPoint: 30,
    maxStock: 120,
    location: "Warehouse A",
    unit: "each",
    cost: 74.25,
    unitPrice: 129.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735002045001",
    vendor: "KeyForge Supply",
    notes: "Low stock because of a delayed vendor shipment.",
  },
  {
    id: "inv-3012",
    sku: "MS-3012",
    product: "Ergonomic Mouse",
    category: "Electronics",
    description: "Right-handed ergonomic mouse for office workstation bundles.",
    stock: 8,
    reorderPoint: 25,
    maxStock: 90,
    location: "Warehouse B",
    unit: "each",
    cost: 22,
    unitPrice: 49.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735003012001",
    vendor: "Deskline Wholesale",
    notes: "Pair with keyboard orders when available.",
  },
  {
    id: "inv-4023",
    sku: "MN-4023",
    product: '27" 4K Monitor',
    category: "Electronics",
    description: "27-inch 4K monitor for workstation and design setups.",
    stock: 0,
    reorderPoint: 12,
    maxStock: 48,
    location: "Warehouse A",
    unit: "each",
    cost: 241.75,
    unitPrice: 349.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735004023001",
    vendor: "DisplaySource",
    notes: "Out of stock. Consider alternate monitor until next delivery.",
  },
  {
    id: "inv-5067",
    sku: "CH-5067",
    product: "Office Chair Premium",
    category: "Furniture",
    description: "Adjustable office chair with lumbar support.",
    stock: 67,
    reorderPoint: 20,
    maxStock: 80,
    location: "Warehouse C",
    unit: "each",
    cost: 188,
    unitPrice: 299.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735005067001",
    vendor: "WorkWell Furniture",
    notes: "Bulky item. Confirm delivery capacity for larger orders.",
  },
  {
    id: "inv-6078",
    sku: "DS-6078",
    product: "Standing Desk Frame",
    category: "Furniture",
    description: "Adjustable standing desk frame without desktop surface.",
    stock: 12,
    reorderPoint: 18,
    maxStock: 50,
    location: "Warehouse C",
    unit: "each",
    cost: 295,
    unitPrice: 449.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735006078001",
    vendor: "WorkWell Furniture",
    notes: "Low stock. Usually sold with cable tray accessories.",
  },
  {
    id: "inv-7089",
    sku: "WC-7089",
    product: "HD Webcam 1080p",
    category: "Electronics",
    description: "USB webcam with built-in microphone.",
    stock: 234,
    reorderPoint: 60,
    maxStock: 300,
    location: "Warehouse B",
    unit: "each",
    cost: 38.75,
    unitPrice: 79.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735007089001",
    vendor: "Northstar Audio",
    notes: "Healthy stock level.",
  },
  {
    id: "inv-8034",
    sku: "HS-8034",
    product: "USB-C Hub 7-in-1",
    category: "Accessories",
    description: "Seven-port USB-C hub with HDMI and card reader.",
    stock: 5,
    reorderPoint: 20,
    maxStock: 100,
    location: "Warehouse A",
    unit: "each",
    cost: 18.4,
    unitPrice: 39.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735008034001",
    vendor: "PortWorks",
    notes: "Critical for laptop accessory bundles.",
  },
  {
    id: "inv-9045",
    sku: "LP-9045",
    product: "Laptop Stand Aluminum",
    category: "Accessories",
    description: "Foldable aluminum laptop stand.",
    stock: 89,
    reorderPoint: 25,
    maxStock: 125,
    location: "Warehouse B",
    unit: "each",
    cost: 27.5,
    unitPrice: 59.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735009045001",
    vendor: "PortWorks",
    notes: "Good add-on product for remote work kits.",
  },
  {
    id: "inv-1056",
    sku: "CB-1056",
    product: "Braided USB-C Cable 2m",
    category: "Accessories",
    description: "Two-meter braided USB-C charging cable.",
    stock: 456,
    reorderPoint: 100,
    maxStock: 500,
    location: "Warehouse A",
    unit: "each",
    cost: 5.1,
    unitPrice: 14.99,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "735001056001",
    vendor: "PortWorks",
    notes: "High-volume accessory with stable margins.",
  },
];
