export type MockInventoryItem = {
  barcode?: string;
  category: string;
  cost: number;
  description: string;
  id: string;
  itemStatus: "Active" | "Inactive";
  location: string;
  maxStock: number;
  notes?: string;
  product: string;
  reorderPoint: number;
  sku: string;
  stock: number;
  taxable: boolean;
  taxRate: number;
  unit: string;
  unitPrice: number;
  vendor?: string;
};

export const mockInventoryItems: MockInventoryItem[] = [
  {
    id: "demo-inventory-101",
    sku: "HVAC-101",
    product: "Smart Thermostat Pro",
    category: "HVAC",
    description: "Wi-Fi thermostat with multi-stage HVAC support.",
    stock: 38,
    reorderPoint: 12,
    maxStock: 60,
    location: "Main Warehouse",
    unit: "each",
    cost: 118,
    unitPrice: 219,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700101000001",
    vendor: "Northwind Controls",
    notes: "Healthy demo stock for upcoming installations.",
  },
  {
    id: "demo-inventory-205",
    sku: "HVAC-205",
    product: "MERV 11 Filter 3-Pack",
    category: "HVAC",
    description: "Three-pack of pleated replacement air filters.",
    stock: 15,
    reorderPoint: 15,
    maxStock: 80,
    location: "Service Van A",
    unit: "pack",
    cost: 19,
    unitPrice: 42,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700205000001",
    vendor: "AirFlow Supply",
    notes: "At reorder point for a visible demo restock signal.",
  },
  {
    id: "demo-inventory-330",
    sku: "HVAC-330",
    product: "Condensate Pump",
    category: "HVAC",
    description: "Compact replacement condensate removal pump.",
    stock: 0,
    reorderPoint: 6,
    maxStock: 24,
    location: "Main Warehouse",
    unit: "each",
    cost: 58,
    unitPrice: 119,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700330000001",
    vendor: "AirFlow Supply",
    notes: "Out of stock to demonstrate critical inventory status.",
  },
  {
    id: "demo-inventory-310",
    sku: "PLB-310",
    product: "Leak Sensor Starter Kit",
    category: "Plumbing",
    description: "Connected leak sensors with a compact hub.",
    stock: 24,
    reorderPoint: 8,
    maxStock: 40,
    location: "Showroom",
    unit: "kit",
    cost: 44,
    unitPrice: 89,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700310000001",
    vendor: "AquaGuard",
    notes: "Popular add-on for water heater and fixture work.",
  },
  {
    id: "demo-inventory-420",
    sku: "PLB-420",
    product: "Braided Supply Line Pair",
    category: "Plumbing",
    description: "Stainless braided faucet supply lines.",
    stock: 54,
    reorderPoint: 20,
    maxStock: 100,
    location: "Service Van A",
    unit: "pair",
    cost: 11,
    unitPrice: 26,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700420000001",
    vendor: "FlowLine Wholesale",
    notes: "High-turn demo inventory item.",
  },
  {
    id: "demo-inventory-515",
    sku: "PLB-515",
    product: "Quarter-Turn Shutoff Kit",
    category: "Plumbing",
    description: "Valve, escutcheon, and installation hardware.",
    stock: 10,
    reorderPoint: 10,
    maxStock: 50,
    location: "Main Warehouse",
    unit: "kit",
    cost: 16,
    unitPrice: 38,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700515000001",
    vendor: "FlowLine Wholesale",
    notes: "At reorder point for demo inventory health reporting.",
  },
  {
    id: "demo-inventory-620",
    sku: "ELC-620",
    product: "LED Floodlight Pair",
    category: "Electrical",
    description: "Weather-rated adjustable LED floodlights.",
    stock: 31,
    reorderPoint: 10,
    maxStock: 60,
    location: "Main Warehouse",
    unit: "pair",
    cost: 52,
    unitPrice: 109,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700620000001",
    vendor: "BrightCircuit",
    notes: "Fictional electrical inventory for product screenshots.",
  },
  {
    id: "demo-inventory-735",
    sku: "ELC-735",
    product: "Weatherproof GFCI Outlet",
    category: "Electrical",
    description: "Outdoor-rated GFCI outlet with cover.",
    stock: 18,
    reorderPoint: 8,
    maxStock: 40,
    location: "Service Van A",
    unit: "each",
    cost: 21,
    unitPrice: 49,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700735000001",
    vendor: "BrightCircuit",
    notes: "Healthy demo stock.",
  },
  {
    id: "demo-inventory-810",
    sku: "ACC-810",
    product: "Technician Tool Tote",
    category: "Accessories",
    description: "Structured technician tote with removable dividers.",
    stock: 15,
    reorderPoint: 6,
    maxStock: 30,
    location: "Showroom",
    unit: "each",
    cost: 48,
    unitPrice: 96,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700810000001",
    vendor: "FieldReady Gear",
    notes: "Fictional accessory item.",
  },
  {
    id: "demo-inventory-925",
    sku: "ACC-925",
    product: "Digital Inspection Camera",
    category: "Accessories",
    description: "Compact inspection camera with flexible probe.",
    stock: 9,
    reorderPoint: 5,
    maxStock: 20,
    location: "Main Warehouse",
    unit: "each",
    cost: 132,
    unitPrice: 249,
    taxable: true,
    taxRate: 8.25,
    itemStatus: "Active",
    barcode: "700925000001",
    vendor: "FieldReady Gear",
    notes: "Fictional high-value accessory.",
  },
];
